service: nextjs-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  memorySize: 2048
  timeout: 30
  environment:
    STATIC_BUCKET_NAME: blog.comaytime.store
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::blog.comaytime.store/*

custom:
  serverless-nextjs:
    component: "@sls-next/serverless-component"
    assetsBucketName: blog.comaytime.store
    cloudfrontDistributionId: EHCDSJ6EITDZD

package:
  individually: true
  patterns:
    - "!.next/cache/**" # ✅ Exclude build cache

